version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gestao_materiais
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gtadmin
    ports:
      - "5433:5432"
        
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: gtadmin@domain.com
      PGADMIN_DEFAULT_PASSWORD: gtroot
    ports:
      - "8080:80"

  backend:
    build: ./backend
    command: >
      bash -c "chmod +x backend.sh &&/bin/bash backend.sh"

    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: npm start 0.0.0.0:3000
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
